CREATE TABLE IF NOT EXISTS votes (
    id SERIAL PRIMARY KEY,
    candidate VARCHAR(3) NOT NULL,
    state VARCHAR(3) NOT NULL,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE votes ADD INDEX (candidate);
ALTER TABLE votes ADD INDEX (state);